export const actividad: Record<string, string> = {
    'actividad.titulo': 'Mi Actividad',
    'actividad.descripcion': 'Historial de eventos, operaciones y sesiones',
    'actividad.timeline': 'Timeline',
    'actividad.bitacora': 'Bitácora',
    'actividad.operaciones': 'Operaciones',
    'actividad.eventosSeg': 'Eventos de Seguridad',
    'actividad.logins': 'logins',
    'actividad.fallidos': 'fallidos',
    'actividad.opInventario': 'Operaciones Inventario',
    'actividad.conteosRealizados': 'Conteos Realizados',
    'actividad.ultimoLogin': 'Último Inicio de Sesión',
    'actividad.ip': 'IP:',
    'actividad.sinLoginReg': 'Sin registros de inicio de sesión',
    'actividad.ultimaOp': 'Última Operación',
    'actividad.sinOpReg': 'Sin operaciones registradas',
    'actividad.desglose': 'Desglose de Actividad en el Período',
    'actividad.iniciosSesion': 'Inicios de Sesión',
    'actividad.cronologica': 'Actividad Cronológica',
    'actividad.eventos': 'eventos',
    'actividad.sinActividad': 'No hay actividad registrada en el período',
    'actividad.tipoEvento': 'Tipo de evento',
    'actividad.inicioSesion': 'Inicio de sesión',
    'actividad.loginFallido': 'Login fallido',
    'actividad.cierreSesion': 'Cierre de sesión',
    'actividad.cambioContrasena': 'Cambio contraseña',
    'actividad.recupContrasena': 'Recuperación contraseña',
    'actividad.bloqueoCuenta': 'Bloqueo cuenta',
    'actividad.desbloqueo': 'Desbloqueo cuenta',
    'actividad.dispNuevo': 'Dispositivo nuevo',
    'actividad.accesoDenegado': 'Acceso denegado',
    'actividad.sesionForzada': 'Sesión forzada',
    'actividad.multIntentos': 'Múltiples intentos',
    'actividad.severidad': 'Severidad',
    'actividad.informacion': 'Información',
    'actividad.advertencia': 'Advertencia',
    'actividad.error': 'Error',
    'actividad.critico': 'Crítico',
    'actividad.opInventarioTit': 'Operaciones de Inventario',
    'actividad.sinOpFiltros': 'No se encontraron operaciones con los filtros seleccionados',
    'actividad.histSesiones': 'Historial de Sesiones',
    'actividad.activa': 'Activa',
    'actividad.cerrada': 'Cerrada',
    'actividad.expirada': 'Expirada',
    'actividad.sinSesionesPeriodo': 'No se encontraron sesiones en el período',
    'actividad.sinEventos': 'No se encontraron eventos de seguridad',
    'actividad.sesiones': 'Sesiones',
    'actividad.seguridad': 'Seguridad',
    'actividad.inventario': 'Inventario',
    'actividad.conteo': 'Conteo',
    'actividad.buscarDesc': 'Buscar en descripción...',
};
