export const comun: Record<string, string> = {
    'tiempo.ahoraMismo': 'Ahora mismo',
    'tiempo.haceMin': 'Hace {n} min',
    'tiempo.haceHoras': 'Hace {n} h',
    'tiempo.haceDias': 'Hace {n} d',

    'comun.cargando': 'Cargando...',
    'comun.cargandoPerfil': 'Cargando perfil...',
    'comun.cargandoDashboard': 'Cargando datos del dashboard...',
    'comun.cargandoTurno': 'Cargando información del turno...',
    'comun.cargandoTransferencias': 'Cargando transferencias...',
    'comun.cargandoConteos': 'Cargando conteos...',
    'comun.cargandoProductos': 'Cargando productos...',
    'comun.cargandoDetalle': 'Cargando detalle...',
    'comun.cargandoEntradas': 'Cargando entradas...',
    'comun.cargandoSalidas': 'Cargando salidas...',
    'comun.cargandoStock': 'Cargando stock...',
    'comun.cargandoNotificaciones': 'Cargando notificaciones...',
    'comun.cargandoDatos': 'Cargando datos...',
    'comun.generandoReporte': 'Generando reporte...',
    'comun.buscandoProductos': 'Buscando productos...',
    'comun.cancelar': 'Cancelar',
    'comun.confirmar': 'Confirmar',
    'comun.buscar': 'Buscar',
    'comun.guardar': 'Guardar',
    'comun.cerrar': 'Cerrar',
    'comun.exportarCsv': 'Exportar CSV',
    'comun.filtrar': 'Filtrar',
    'comun.limpiar': 'Limpiar',
    'comun.guardarCambios': 'Guardar cambios',
    'comun.producto': 'Producto',
    'comun.cantidad': 'Cantidad',
    'comun.motivo': 'Motivo',
    'comun.estado': 'Estado',
    'comun.tipo': 'Tipo',
    'comun.fecha': 'Fecha',
    'comun.acciones': 'Acciones',
    'comun.descripcion': 'Descripción',
    'comun.precio': 'Precio',
    'comun.stock': 'Stock',
    'comun.sku': 'SKU',
    'comun.almacen': 'Almacén',
    'comun.todos': 'Todos',
    'comun.todas': 'Todas',
    'comun.desde': 'Desde',
    'comun.hasta': 'Hasta',
    'comun.productoSku': 'Producto o SKU...',
    'comun.escribaBuscar': 'Escriba para buscar producto por nombre o SKU...',
    'comun.observaciones': 'Observaciones opcionales...',
    'comun.tipoDocumento': 'Tipo de documento',
    'comun.numDocumento': 'Número de documento',
    'comun.notasAdicionales': 'Notas adicionales',
    'comun.notasOpcional': 'Notas (opcional)',
    'comun.observacionesCambio': 'Observaciones sobre el cambio de estado...',
    'comun.sinDocumento': 'Sin documento',
    'comun.factura': 'Factura',
    'comun.otro': 'Otro',
    'comun.ordenCompra': 'Orden de compra',
    'comun.guiaRemision': 'Guía de remisión',
    'comun.notaEntrega': 'Nota de entrega',
    'comun.ordenDespacho': 'Orden de despacho',
    'comun.motivoEjEntrada': 'Ej: Compra a proveedor, reposición de stock...',
    'comun.motivoEjSalida': 'Ej: Venta directa, despacho a cliente...',
    'comun.numDocEjEntrada': 'Ej: FAC-001234',
    'comun.numDocEjSalida': 'Ej: OD-001234',
    'comun.anterior': 'Anterior',
    'comun.nuevo': 'Nuevo',
    'comun.colaborador': 'Colaborador',
    'comun.ip': 'IP',
    'comun.navegador': 'Navegador',
    'comun.sistema': 'Sistema',
    'comun.cierre': 'Cierre',
    'comun.ubicacion': 'Ubicación',
    'comun.programado': 'Programado',
    'comun.completado': 'Completado',
    'comun.completada': 'Completada',
    'comun.aprobado': 'Aprobado',
    'comun.rechazado': 'Rechazado',
    'comun.cancelado': 'Cancelado',
    'comun.cancelada': 'Cancelada',
    'comun.pendiente': 'Pendiente',
    'comun.nombre': 'Nombre',
    'comun.direccion': 'Dirección',
    'comun.dia': 'Día',
    'comun.horas': 'Horas',
    'comun.noProductosFiltro': 'No se encontraron productos',
    'comun.productos': 'productos',
    'comun.limpiarFiltros': 'Limpiar filtros',
    'comun.verDetalle': 'Ver detalle',
    'comun.completar': 'Completar',
    'comun.ent': 'ent.',
    'comun.sal': 'sal.',
    'comun.mov': 'mov.',
    'comun.sinStock': 'Sin asignar',
    'comun.ordenTransferencia': 'Orden de transferencia',
    'comun.guiaDespacho': 'Guía de despacho',
    'comun.notaTraslado': 'Nota de traslado',
    'comun.motivoEjTransferencia': 'Ej: Reabastecimiento, redistribución de stock...',
    'comun.numDocEjTransferencia': 'Ej: OT-001234',
    'comun.stockDisponible': 'Stock disponible',
    'comun.origen': 'Origen',
    'comun.destino': 'Destino',
    'comun.documento': 'Documento',
    'comun.notas': 'Notas',
    'comun.codigo': 'Código',
    'comun.telefono': 'Teléfono',
    'comun.fechaDesde': 'Fecha desde',
    'comun.fechaHasta': 'Fecha hasta',
    'comun.diferencia': 'Diferencia',
    'comun.usuario': 'Usuario',
    'comun.inicio': 'Inicio',
    'comun.ultimaActividad': 'Última Actividad',

    'toast.campoRequerido': 'Campo requerido',
    'toast.camposRequeridos': 'Campos requeridos',
    'toast.almacenesIguales': 'Almacenes iguales',
    'toast.stockInsuficiente': 'Stock insuficiente',
    'toast.transferenciaCreada': 'Transferencia creada',
    'toast.estadoActualizado': 'Estado actualizado',
    'toast.entradaRegistrada': 'Entrada registrada',
    'toast.salidaRegistrada': 'Salida registrada',
    'toast.conteoProgramado': 'Conteo programado',
    'toast.enProgreso': 'En progreso',
    'toast.registrado': 'Registrado',
    'toast.loteGuardado': 'Lote guardado',
    'toast.sinCambios': 'Sin cambios',
    'toast.cantidadInvalida': 'Cantidad inválida',
    'toast.exportIniciada': 'Exportación iniciada',
    'toast.seleccioneProducto': 'Seleccione un producto',
    'toast.seleccioneOrigen': 'Seleccione el almacén de origen',
    'toast.seleccioneDestino': 'Seleccione el almacén de destino',
    'toast.almacenesIgualesMsg': 'El almacén de origen y destino no pueden ser el mismo',
    'toast.motivoInvalido': 'Ingrese un motivo válido (mínimo 3 caracteres)',
    'toast.stockInsufMsg': 'Stock insuficiente. Disponible: {disponible}, Solicitado: {solicitado}',
    'toast.errorCrearTransferencia': 'Error al crear la transferencia',
    'toast.errorActualizarEstado': 'Error al actualizar el estado',
    'toast.completeCampos': 'Complete todos los campos obligatorios',
    'toast.errorRegistrarEntrada': 'Error al registrar la entrada',
    'toast.errorRegistrarSalida': 'Error al registrar la salida',
    'toast.errorCargarDatos': 'Error al cargar datos iniciales',
    'toast.errorCargarProductos': 'Error al cargar productos',
    'toast.errorCargarDetalle': 'Error al cargar detalle del producto',
    'toast.errorCargarNotif': 'No se pudieron cargar las notificaciones',
    'toast.notifLeida': 'Notificación marcada como leída',
    'toast.errorMarcarNotif': 'Error al marcar la notificación',
    'toast.notifArchivada': 'Notificación archivada',
    'toast.errorArchivarNotif': 'Error al archivar la notificación',
    'toast.notifEliminada': 'Notificación eliminada',
    'toast.errorEliminarNotif': 'Error al eliminar la notificación',
    'toast.todasLeidas': 'Todas las notificaciones marcadas como leídas',
    'toast.errorMarcarTodas': 'Error al marcar notificaciones',
    'toast.notifsSelLeidas': '{n} notificaciones marcadas como leídas',
    'toast.leidasArchivadas': 'Notificaciones leídas archivadas',
    'toast.errorArchivarTodas': 'Error al archivar notificaciones',
    'toast.errorRegistrarEntradaTurno': 'Error al registrar entrada',
    'toast.errorRegistrarSalidaTurno': 'Error al registrar salida',
    'toast.errorCargarPerfil': 'No se pudo cargar el perfil',
    'toast.errorCargarSeguridad': 'No se pudo cargar la información de seguridad',
    'toast.errorCargarPreferencias': 'No se pudieron cargar las preferencias',
    'toast.errorCargarSesiones': 'No se pudieron cargar las sesiones',
    'toast.errorCargarDispositivos': 'No se pudieron cargar los dispositivos',
    'toast.nombreApellidoReq': 'Nombre y apellido son requeridos',
    'toast.errorActualizarPerfil': 'No se pudo actualizar el perfil',
    'toast.ingreseContrasenaActual': 'Ingrese su contraseña actual',
    'toast.contrasenasNoCoinciden': 'Las contraseñas no coinciden',
    'toast.errorCambiarContrasena': 'No se pudo cambiar la contraseña',
    'toast.errorActualizarSeguridad': 'No se pudo actualizar la seguridad',
    'toast.errorGuardarPreferencias': 'No se pudieron guardar las preferencias',
    'toast.errorCerrarSesion': 'No se pudo cerrar la sesión',
    'toast.errorCerrarSesiones': 'No se pudieron cerrar las sesiones',
    'toast.errorEliminarDisp': 'No se pudo eliminar el dispositivo',
    'toast.errorActualizarDisp': 'No se pudo actualizar el dispositivo',
    'toast.errorRenombrarDisp': 'No se pudo renombrar el dispositivo',
    'toast.seleccioneAlmacen': 'Seleccione un almacén',
    'toast.seleccioneFecha': 'Seleccione la fecha programada',
    'toast.conteoProgramadoMsg': 'Conteo programado exitosamente',
    'toast.errorCrearConteo': 'Error al crear el conteo',
    'toast.errorCargarDetConteo': 'Error al cargar el detalle',
    'toast.conteoIniciado': 'Conteo iniciado',
    'toast.errorIniciarConteo': 'Error al iniciar el conteo',
    'toast.cantidadInvalidaMsg': 'Ingrese una cantidad válida (0 o mayor)',
    'toast.productoRegistrado': 'Producto registrado',
    'toast.errorRegistrar': 'Error al registrar',
    'toast.sinProductosCantidad': 'No hay productos con cantidades para registrar',
    'toast.loteRegistrado': 'Lote registrado',
    'toast.errorGuardarLote': 'Error al guardar lote',
    'toast.errorCargarResumen': 'Error al cargar resumen de actividad',
    'toast.errorCargarBitacora': 'Error al cargar bitácora',
    'toast.errorCargarOperaciones': 'Error al cargar operaciones',
    'toast.errorCargarSesionesMi': 'Error al cargar sesiones',
    'toast.errorCargarTimeline': 'Error al cargar timeline',
    'toast.exportBitacora': 'Exportación de bitácora iniciada',
    'toast.exportOperaciones': 'Exportación de operaciones iniciada',
    'toast.errorCargarResumenRep': 'Error al cargar resumen de reportes',
    'toast.errorCargarMovimientos': 'Error al cargar movimientos',
    'toast.errorCargarStockCritico': 'Error al cargar stock crítico',
    'toast.errorCargarActividadRep': 'Error al cargar actividad',

    'contrasena.min12': 'La contraseña debe tener al menos 12 caracteres',
    'contrasena.mayuscula': 'Debe contener al menos una mayúscula',
    'contrasena.minuscula': 'Debe contener al menos una minúscula',
    'contrasena.numero': 'Debe contener al menos un número',
    'contrasena.especial': 'Debe contener al menos un carácter especial',
    'contrasena.debil': 'Débil',
    'contrasena.media': 'Media',
    'contrasena.fuerte': 'Fuerte',
    'contrasena.muyFuerte': 'Muy fuerte',

    'etiqueta.disponible': 'Disponible',
    'etiqueta.enTransito': 'En Tránsito',
    'etiqueta.enCurso': 'En Curso',
    'etiqueta.finalizado': 'Finalizado',
    'etiqueta.anticipado': 'Anticipado',
    'etiqueta.puntual': 'Puntual',
    'etiqueta.leveRetraso': 'Leve retraso',
    'etiqueta.retraso': 'Retraso',
    'etiqueta.transfSalida': 'Transferencia (S)',
    'etiqueta.transfEntrada': 'Transferencia (E)',
    'etiqueta.programado': 'Programado',
    'etiqueta.enProgresoLabel': 'En Progreso',
    'etiqueta.completado': 'Completado',
    'etiqueta.aprobado': 'Aprobado',
    'etiqueta.rechazado': 'Rechazado',
    'etiqueta.cancelado': 'Cancelado',

    'contrato.permanente': 'Permanente',
    'contrato.temporal': 'Temporal',
    'contrato.medioTiempo': 'Medio tiempo',
    'contrato.pasantia': 'Pasantía',
    'contrato.porContrato': 'Por contrato',

    'misc.noDisponible': 'No disponible',
    'misc.nunca': 'Nunca',

    'login.errorInicioSesion': 'Error al iniciar sesión',
    'login.sinAcceso': 'Tu cuenta no tiene acceso al portal de colaboradores. Verifica que tu rol sea el correcto.',
    'login.errorConexion': 'Error de conexión con el servidor',
};
