export const conteos: Record<string, string> = {
    'conteos.titulo': 'Conteos de Inventario',
    'conteos.nuevo': 'Nuevo Conteo',
    'conteos.programados': 'Programados',
    'conteos.enProgreso': 'En Progreso',
    'conteos.finalizadosMes': 'Finalizados este mes',
    'conteos.totalMes': 'Total del mes',
    'conteos.sinRegistros': 'Sin conteos registrados',
    'conteos.noEncontrados': 'No se encontraron conteos con los filtros aplicados',
    'conteos.programarPrimero': 'Programar primer conteo',
    'conteos.encontrados': 'conteos encontrados',
    'conteos.zona': 'Zona:',
    'conteos.parcial': 'Parcial',
    'conteos.completo': 'Completo',
    'conteos.iniciar': 'Iniciar conteo',
    'conteos.continuar': 'Continuar conteo',
    'conteos.aprobar': 'Aprobar',
    'conteos.rechazar': 'Rechazar',
    'conteos.volverLista': 'Volver a la lista',
    'conteos.responsable': 'Responsable',
    'conteos.fechaProgramada': 'Fecha programada',
    'conteos.zonaConteo': 'Zona de conteo',
    'conteos.notas': 'Notas',
    'conteos.productosContados': 'Productos contados',
    'conteos.discrepancias': 'Discrepancias',
    'conteos.unidFaltantes': 'Unid. faltantes',
    'conteos.unidSobrantes': 'Unid. sobrantes',
    'conteos.inicio': 'Inicio:',
    'conteos.fin': 'Fin:',
    'conteos.programar': 'Programar Conteo',
    'conteos.salir': 'Salir',
    'conteos.registrarConteo': 'Registrar conteo',
    'conteos.guardarTodo': 'Guardar todo',
    'conteos.stockSistema': 'Stock sistema',
    'conteos.cantidadFisica': 'Cantidad física',
    'conteos.contado': 'Contado',
    'conteos.guardar': 'Guardar',
    'conteos.sinProductosFiltro': 'No se encontraron productos con ese filtro',
    'conteos.parcialDesc': 'Solo productos de zona/categoría específica',
    'conteos.completoDesc': 'Todos los productos del almacén',
    'conteos.todasCategorias': 'Todas las categorías',
    'conteos.instrucciones': 'Instrucciones o notas para el conteo...',
    'conteos.ajustarStock': 'Ajustar stock automáticamente',
    'conteos.ajustarDesc': 'El stock de los productos se actualizará según las cantidades del conteo físico',
    'conteos.aprobarIrreversible': 'Al aprobar con ajuste de stock, los cambios son irreversibles.',
    'conteos.cancelarInfo': 'Los datos de conteo registrados se mantendrán pero el conteo quedará como cancelado.',
    'conteos.rechazarInfo': 'El conteo podrá reanudarse desde el estado "En Progreso" para corregir las observaciones.',
    'conteos.categoriaEspecifica': 'Categoría específica',
    'conteos.buscarProductoSku': 'Buscar producto por nombre o SKU...',
    'conteos.ejZona': 'Ej: Pasillo A, Estante 3...',
};
