export const inventario: Record<string, string> = {
    'entradas.titulo': 'Entradas de Inventario',
    'entradas.nueva': 'Nueva Entrada',
    'entradas.sinRegistros': 'Sin entradas registradas',
    'entradas.noEncontrados': 'No se encontraron registros de entrada',
    'entradas.registrarPrimera': 'Registrar primera entrada',
    'entradas.registrar': 'Registrar Entrada',

    'salidas.titulo': 'Salidas de Inventario',
    'salidas.nueva': 'Nueva Salida',
    'salidas.sinRegistros': 'Sin salidas registradas',
    'salidas.noEncontrados': 'No se encontraron registros de salida',
    'salidas.registrarPrimera': 'Registrar primera salida',
    'salidas.registrar': 'Registrar Salida',
    'salidas.stockDisponible': 'Stock disponible:',

    'stock.titulo': 'Stock General',
    'stock.buscar': 'Buscar producto',
    'stock.placeholder': 'Nombre o SKU...',
    'stock.todosAlmacenes': 'Todos los almacenes',
    'stock.noEncontrados': 'No se encontraron productos',
    'stock.intentaFiltros': 'Intenta con otros filtros de búsqueda',
    'stock.productos': 'productos',
    'stock.almacen': 'Almacén',
    'stock.producto': 'Producto',
    'stock.categoria': 'Categoría',
    'stock.precio': 'Precio',
    'stock.stockCol': 'Stock',
    'stock.min': 'Min.',
    'stock.estado': 'Estado',

    'transferencias.titulo': 'Transferencias entre Almacenes',
    'transferencias.nueva': 'Nueva Transferencia',
    'transferencias.sinRegistros': 'Sin transferencias registradas',
    'transferencias.noEncontrados': 'No se encontraron transferencias con los filtros aplicados',
    'transferencias.crearPrimera': 'Crear primera transferencia',
    'transferencias.crear': 'Crear Transferencia',
    'transferencias.encontradas': 'transferencias encontradas',
    'transferencias.detalle': 'Detalle de Transferencia',
    'transferencias.unidades': 'unidades',
    'transferencias.almacenOrigen': 'Almacén Origen',
    'transferencias.almacenDestino': 'Almacén Destino',
    'transferencias.seleccioneOrigen': 'Seleccione origen',
    'transferencias.seleccioneDestino': 'Seleccione destino',
    'transferencias.soloAsignados': 'Solo almacenes asignados',
    'transferencias.todosActivos': 'Todos los almacenes activos',
    'transferencias.pendienteInfo': 'La transferencia quedará en estado <strong>Pendiente</strong> hasta que sea aprobada. El stock no se modificará hasta que se marque como <strong>Completada</strong>.',
    'transferencias.marcarEnTransito': 'Marcar En Tránsito',
    'transferencias.completar': 'Completar Transferencia',
    'transferencias.cancelar': 'Cancelar Transferencia',
    'transferencias.alCompletar': 'Al completar, el stock del producto se descontará del almacén de origen.',
    'transferencias.accionIrreversible': 'Esta acción no se puede deshacer.',
    'transferencias.movimientoStock': 'Movimiento de stock',
    'transferencias.solicitadoPor': 'Solicitado por',
    'transferencias.enTransito': 'En Tránsito',
};
