export const notificaciones: Record<string, string> = {
    'notif.titulo': 'Notificaciones',
    'notif.descripcion': 'Gestiona tus notificaciones del sistema',
    'notif.enTotal': 'en total',
    'notif.marcarLeidas': 'Marcar todas como leídas',
    'notif.archivarLeidas': 'Archivar leídas',
    'notif.bandeja': 'Bandeja',
    'notif.sinLeer': 'Sin leer',
    'notif.archivadas': 'Archivadas',
    'notif.buscar': 'Buscar en notificaciones...',
    'notif.todosLosTipos': 'Todos los tipos',
    'notif.exito': 'Éxito',
    'notif.importante': 'Importante',
    'notif.sistema': 'Sistema',
    'notif.seleccionadas': 'notificación(es) seleccionada(s)',
    'notif.marcarSelLeidas': 'Marcar como leídas',
    'notif.seleccionarTodas': 'Seleccionar todas',
    'notif.nueva': 'Nueva',
    'notif.marcarLeida': 'Marcar como leída',
    'notif.archivar': 'Archivar',
    'notif.eliminar': 'Eliminar',
    'notif.sinSinLeer': 'No hay notificaciones sin leer',
    'notif.alDia': '¡Estás al día con todas tus notificaciones!',
    'notif.sinArchivadas': 'No hay notificaciones archivadas',
    'notif.archivadasDesc': 'Las notificaciones que archives aparecerán aquí',
    'notif.sinNotif': 'No hay notificaciones',
    'notif.sinNotifDesc': 'Recibirás notificaciones cuando haya actividad en el sistema',
    'notif.informacion': 'Información',
    'notif.advertencia': 'Advertencia',
    'notif.pagina': 'Página',
    'notif.de': 'de',
    'notif.notificaciones': 'notificaciones',
};
