export const perfil: Record<string, string> = {
    'perfil.sinCargo': 'Sin cargo asignado',
    'perfil.desde': 'Desde',
    'perfil.ultimoAcceso': 'Último acceso:',
    'perfil.verificado': 'Verificado',

    'perfil.general': 'General',
    'perfil.seguridad': 'Seguridad',
    'perfil.preferencias': 'Preferencias',
    'perfil.sesiones': 'Sesiones',
    'perfil.dispositivos': 'Dispositivos',

    'perfil.infoPersonal': 'Información Personal',
    'perfil.editar': 'Editar',
    'perfil.nombre': 'Nombre',
    'perfil.apellido': 'Apellido',
    'perfil.telefono': 'Teléfono',
    'perfil.genero': 'Género',
    'perfil.noEspecificado': 'No especificado',
    'perfil.masculino': 'Masculino',
    'perfil.femenino': 'Femenino',
    'perfil.contactoEmergencia': 'Contacto de Emergencia',
    'perfil.nombreContacto': 'Nombre del contacto',
    'perfil.nombreCompleto': 'Nombre completo',
    'perfil.telefonoEmergencia': 'Teléfono de emergencia',
    'perfil.ejTelefono': 'Ej: +504 9999-9999',
    'perfil.identidad': 'Identidad',
    'perfil.noRegistrada': 'No registrada',
    'perfil.fechaNacimiento': 'Fecha de nacimiento',
    'perfil.noRegistrado': 'No registrado',

    'perfil.infoLaboral': 'Información Laboral',
    'perfil.codigo': 'Código',
    'perfil.cargo': 'Cargo',
    'perfil.sinCargoPuesto': 'Sin cargo',
    'perfil.tipoContrato': 'Tipo de contrato',
    'perfil.fechaIngreso': 'Fecha de ingreso',
    'perfil.almacenPrincipal': 'Almacén principal',

    'perfil.rolesAlmacenes': 'Roles y Almacenes',
    'perfil.rolesAsignados': 'Roles asignados',
    'perfil.sinRoles': 'Sin roles asignados',
    'perfil.almacenesAsignados': 'Almacenes asignados',
    'perfil.sinAlmacenes': 'Sin almacenes asignados',

    'seguridad.contrasena': 'Contraseña',
    'seguridad.estadoContrasena': 'Estado de la contraseña',
    'seguridad.contrasenaTemporal': 'Contraseña temporal - debe cambiarla',
    'seguridad.ultimoCambio': 'Último cambio:',
    'seguridad.dias': 'días',
    'seguridad.cambiarContrasena': 'Cambiar contraseña',
    'seguridad.contrasenaActual': 'Contraseña actual',
    'seguridad.ingreseActual': 'Ingrese su contraseña actual',
    'seguridad.nuevaContrasena': 'Nueva contraseña',
    'seguridad.minCaracteres': 'Mínimo 12 caracteres',
    'seguridad.12Caracteres': '12+ caracteres',
    'seguridad.mayuscula': 'Mayúscula',
    'seguridad.minuscula': 'Minúscula',
    'seguridad.numero': 'Número',
    'seguridad.especial': 'Especial',
    'seguridad.confirmarContrasena': 'Confirmar nueva contraseña',
    'seguridad.repitaContrasena': 'Repita la nueva contraseña',
    'seguridad.noCoinciden': 'Las contraseñas no coinciden',

    'seguridad.configuracion': 'Configuración de Seguridad',
    'seguridad.2fa': 'Autenticación de dos factores (2FA)',
    'seguridad.2faDesc': 'Añade una capa adicional de seguridad a tu cuenta',
    'seguridad.2faInactivo': 'No configurado',
    'seguridad.2faActivo': 'Activo',
    'seguridad.activar2fa': 'Activar autenticación de dos factores',
    'seguridad.desactivar2fa': 'Desactivar 2FA',
    'seguridad.desactivarDesc': 'Para desactivar la autenticación de dos factores, ingresa tu contraseña actual',
    'seguridad.contrasenaRequerida': 'Ingresa tu contraseña para continuar',
    'seguridad.seleccionarMetodo': 'Selecciona el método de verificación',
    'seguridad.metodoVerificacion': 'Método de verificación',
    'seguridad.correoElectronico': 'Correo electrónico',
    'seguridad.correoDesc': 'Recibe un código de verificación en tu correo',
    'seguridad.appAutenticadora': 'Aplicación autenticadora',
    'seguridad.appDesc': 'Usa Google Authenticator, Authy u otra app compatible',
    'seguridad.configurando': 'Configurando...',
    'seguridad.cancelar': 'Cancelar',
    'seguridad.verificarCodigo': 'Verificar código',
    'seguridad.escanearQR': 'Escanea este código QR con tu aplicación autenticadora',
    'seguridad.codigoEnviado': 'Se ha enviado un código de verificación a tu correo electrónico',
    'seguridad.ingresarCodigo': 'Código de 6 dígitos',
    'seguridad.codigo6Digitos': 'El código debe tener 6 dígitos',
    'seguridad.codigoIncorrecto': 'El código de verificación es incorrecto',
    'seguridad.confirmarActivacion': 'Confirmar y activar',
    'seguridad.sesionesMaximas': 'Sesiones simultáneas máximas',
    'seguridad.sesion': 'sesión',
    'seguridad.sesiones': 'sesiones',
    'seguridad.controlSesionesAdmin': 'Este valor es configurado por el administrador del sistema',
    'seguridad.guardarConfig': 'Guardar configuración',

    'seguridad.actividadReciente': 'Actividad Reciente de Seguridad',
    'seguridad.sesionesActivas': 'Sesiones activas',
    'seguridad.ultimoCambioContrasena': 'Último cambio de contraseña',
    'seguridad.sinActividad': 'No hay actividad reciente',

    'preferencias.temaColor': 'Tema de Color',
    'preferencias.seleccionaColor': 'Selecciona el color principal de la interfaz',
    'preferencias.interfaz': 'Interfaz',
    'preferencias.sidebarCompacto': 'Sidebar compacto',
    'preferencias.sidebarDesc': 'Reduce el ancho del menú lateral',
    'preferencias.idioma': 'Idioma',
    'preferencias.zonaHoraria': 'Zona horaria',
    'preferencias.notificaciones': 'Notificaciones',
    'preferencias.sonido': 'Sonido de notificaciones',
    'preferencias.sonidoDesc': 'Reproduce un sonido al recibir notificaciones',
    'preferencias.escritorio': 'Notificaciones de escritorio',
    'preferencias.escritorioDesc': 'Muestra notificaciones del sistema operativo',
    'preferencias.guardar': 'Guardar preferencias',

    'sesiones.titulo': 'Sesiones Activas',
    'sesiones.cerrarTodas': 'Cerrar todas las demás',
    'sesiones.actual': 'Actual',
    'sesiones.iniciada': 'Iniciada:',
    'sesiones.ultimaActividad': 'Última actividad:',
    'sesiones.sinSesiones': 'No hay sesiones activas',

    'dispositivos.titulo': 'Dispositivos Registrados',
    'dispositivos.tituloConfianza': 'Mis Dispositivos',
    'dispositivos.descripcion': 'Aquí puedes ver y administrar los dispositivos desde los que has iniciado sesión. Marca como confiables los que reconozcas para mayor seguridad.',
    'dispositivos.confiable': 'Confiable',
    'dispositivos.enLinea': 'En línea',
    'dispositivos.navegadorDesconocido': 'Navegador desconocido',
    'dispositivos.soDesconocido': 'SO desconocido',
    'dispositivos.registrado': 'Registrado:',
    'dispositivos.ultimoUso': 'Último uso:',
    'dispositivos.confirmadoEn': 'Confiable desde:',
    'dispositivos.sinDispositivos': 'No hay dispositivos registrados',
    'dispositivos.sinDispositivosDesc': 'Los dispositivos se registrarán automáticamente cuando inicies sesión.',
    'dispositivos.marcarConfiable': 'Marcar como confiable',
    'dispositivos.revocarConfianza': 'Revocar confianza',
    'dispositivos.renombrar': 'Renombrar dispositivo',
    'dispositivos.eliminar': 'Eliminar dispositivo',
    'dispositivos.nombreMinimo': 'El nombre debe tener al menos 2 caracteres',
};
