export const portal: Record<string, string> = {
    'portal.titulo': 'Portal de Colaboradores',
    'portal.bodega': 'Portal Bodega',
    'portal.soporte': 'Soporte',
    'portal.cerrarSesion': 'Cerrar Sesión',
    'portal.cerrarMenu': 'Cerrar menú',

    'menu.principal': 'Principal',
    'menu.operaciones': 'Operaciones',
    'menu.consultas': 'Consultas',
    'menu.personal': 'Personal',
    'menu.inicio': 'Inicio',
    'menu.miTurno': 'Mi Turno',
    'menu.inventario': 'Inventario',
    'menu.stockGeneral': 'Stock General',
    'menu.entradas': 'Entradas',
    'menu.salidas': 'Salidas',
    'menu.transferencias': 'Transferencias',
    'menu.conteos': 'Conteos',
    'menu.productos': 'Productos',
    'menu.reportes': 'Reportes',
    'menu.miActividad': 'Mi Actividad',
    'menu.notificaciones': 'Notificaciones',
    'menu.miPerfil': 'Mi Perfil',

    'header.notificaciones': 'Notificaciones',
    'header.marcarTodasLeidas': 'Marcar todas como leídas',
    'header.noHayNotificaciones': 'No hay notificaciones',
    'header.verTodas': 'Ver todas las notificaciones',
    'header.miActividad': 'Mi Actividad',
    'header.miTurno': 'Mi Turno',

    'rol.jefeBodega': 'Jefe de Bodega',
    'rol.supervisor': 'Supervisor',
    'rol.inventarista': 'Inventarista',
    'rol.recepcionista': 'Recepcionista',
    'rol.despachador': 'Despachador',
    'rol.auxiliar': 'Auxiliar',
    'rol.consulta': 'Solo Consulta',
    'rol.colaborador': 'Colaborador',
};
