export const productos: Record<string, string> = {
    'productos.catalogo': 'Catálogo de Productos',
    'productos.activos': 'Activos',
    'productos.agotados': 'Agotados',
    'productos.stockBajo': 'Stock Bajo',
    'productos.inactivos': 'Inactivos',
    'productos.buscar': 'Buscar producto',
    'productos.placeholder': 'Nombre, SKU...',
    'productos.categoria': 'Categoría',
    'productos.todas': 'Todas',
    'productos.todos': 'Todos',
    'productos.limpiarFiltros': 'Limpiar filtros',
    'productos.filtrosAvanzados': 'Filtros avanzados',
    'productos.marca': 'Marca',
    'productos.precioDesde': 'Precio desde (L)',
    'productos.precioHasta': 'Precio hasta (L)',
    'productos.aplicarFiltros': 'Aplicar filtros',
    'productos.noEncontrados': 'No se encontraron productos',
    'productos.intentaFiltros': 'Intenta con otros filtros de búsqueda',
    'productos.min': 'Min:',
    'productos.inactivo': 'Inactivo',
    'productos.destacado': 'Destacado',
    'productos.verDetalle': 'Ver detalle',
    'productos.mostrando': 'Mostrando página',
    'productos.de': 'de',
    'productos.resultados': 'resultados',
    'productos.volverCatalogo': 'Volver al catálogo',
    'productos.activo': 'Activo',
    'productos.precioVenta': 'Precio de venta',
    'productos.precioAnterior': 'Precio anterior',
    'productos.costo': 'Costo',
    'productos.margen': 'Margen',
    'productos.stockActual': 'Stock actual',
    'productos.uds': 'uds.',
    'productos.stockMinimo': 'Stock mínimo',
    'productos.estadoStock': 'Estado stock',
    'productos.peso': 'Peso',
    'productos.kg': 'kg',
    'productos.creado': 'Creado',
    'productos.ultimaActualizacion': 'Última actualización',
    'productos.informacion': 'Información',
    'productos.movimientos': 'Movimientos de inventario',
    'productos.descripcion': 'Descripción',
    'productos.sinDescripcion': 'Este producto no tiene descripción detallada.',
    'productos.historialMov': 'Historial de movimientos',
    'productos.todosLosTipos': 'Todos los tipos',
    'productos.ajustes': 'Ajustes',
    'productos.devoluciones': 'Devoluciones',
    'productos.sinMovimientos': 'Sin movimientos registrados',
    'productos.entradas': 'Entradas',
    'productos.salidas': 'Salidas',
    'productos.transferencias': 'Transferencias',
    'productos.stockAnterior': 'Stock anterior',
    'productos.stockNuevo': 'Stock nuevo',
    'productos.agotado': 'Agotado',
};
