export const reportes: Record<string, string> = {
    'reportes.titulo': 'Reportes',
    'reportes.descripcion': 'Consulta y análisis de inventario',
    'reportes.resumen': 'Resumen',
    'reportes.movimientos': 'Movimientos',
    'reportes.stockCritico': 'Stock Crítico',
    'reportes.miActividad': 'Mi Actividad',
    'reportes.generando': 'Generando reporte...',
    'reportes.totalProductos': 'Total Productos',
    'reportes.valorInventario': 'Valor del Inventario',
    'reportes.precioXStock': 'Precio x Stock',
    'reportes.entradasSalidas': 'Entradas / Salidas',
    'reportes.enElPeriodo': 'En el período',
    'reportes.alertasStock': 'Alertas de Stock',
    'reportes.productosMasMovidos': 'Productos Más Movidos',
    'reportes.sinMovPeriodo': 'Sin movimientos en el período',
    'reportes.movPorCategoria': 'Movimientos por Categoría',
    'reportes.sinDatosCategorias': 'Sin datos de categorías',
    'reportes.movInventario': 'Movimientos de Inventario',
    'reportes.registros': 'registros',
    'reportes.tipoOperacion': 'Tipo de operación',
    'reportes.entrada': 'Entrada',
    'reportes.salida': 'Salida',
    'reportes.recepcion': 'Recepción',
    'reportes.despacho': 'Despacho',
    'reportes.ajusteMas': 'Ajuste (+)',
    'reportes.ajusteMenos': 'Ajuste (-)',
    'reportes.transferencia': 'Transferencia',
    'reportes.pagina': 'Página',
    'reportes.totalCriticos': 'Total Críticos',
    'reportes.agotado': 'Agotado',
    'reportes.bajo': 'Bajo',
    'reportes.sinStockCritico': 'No hay productos con stock crítico',
    'reportes.totalOperaciones': 'Total Operaciones',
    'reportes.noMovFiltros': 'No se encontraron movimientos con los filtros seleccionados',
    'reportes.noOpPeriodo': 'No tienes operaciones registradas en el período',
    'reportes.histOperaciones': 'Historial de Operaciones',
    'reportes.buscarProducto': 'Buscar producto...',
    'reportes.placeholderBuscar': 'Nombre o SKU del producto...',
};
