export const turno: Record<string, string> = {
    'turno.turnoHoy': 'Turno de Hoy',
    'turno.resumenSemanal': 'Resumen Semanal',
    'turno.historial': 'Historial',
    'turno.almacen': 'Almacén',
    'turno.inicioProgramado': 'Inicio programado',
    'turno.finProgramado': 'Fin programado',
    'turno.entrada': 'Entrada',
    'turno.salida': 'Salida',
    'turno.pendiente': 'Pendiente',
    'turno.tiempoEnTurno': 'Tiempo en turno',
    'turno.totalHoras': 'Total horas trabajadas',
    'turno.registrarEntrada': 'Registrar Entrada',
    'turno.registrarSalida': 'Registrar Salida',
    'turno.actividadTurno': 'Actividad del Turno',
    'turno.sinTurno': 'Sin turno programado para hoy',
    'turno.sinTurnoDesc': 'No tienes un turno asignado para el día de hoy.',
    'turno.consultaSupervisor': 'Consulta con tu supervisor si crees que esto es un error.',
    'turno.turnosTotales': 'Turnos Totales',
    'turno.completados': 'Completados',
    'turno.horasTrabajadas': 'Horas Trabajadas',
    'turno.puntualidad': 'Puntualidad',
    'turno.turnosSemana': 'Turnos de la Semana',
    'turno.sinTurnosSemana': 'Sin turnos programados esta semana',
    'turno.historialTurnos': 'Historial de Turnos',
    'turno.sinHistorial': 'Sin historial de turnos',
    'turno.registrarEntradaModal': 'Registrar Entrada',
    'turno.registrarSalidaModal': 'Registrar Salida',
    'turno.entradaDesc': 'Estás a punto de registrar tu entrada al turno. Puedes agregar notas opcionales.',
    'turno.salidaDesc': 'Estás a punto de registrar tu salida y finalizar el turno. Puedes agregar notas opcionales.',
    'turno.notasOpcional': 'Notas (opcional)',
    'turno.ejEntrada': 'Ej: Inicio de turno normal, todo en orden...',
    'turno.ejSalida': 'Ej: Turno completado sin novedades...',
    'turno.horaActual': 'Hora actual:',
    'turno.confirmarEntrada': 'Confirmar Entrada',
    'turno.confirmarSalida': 'Confirmar Salida',
    'turno.operacion': 'Operación',
    'turno.hora': 'Hora',
    'turno.notas': 'Notas',
};
