export const PERMISOS_COLAB = {
    ACCESO: 'colab_dashboard.ver',
    TURNO_VER: 'colab_turno.ver',
    TURNO_REGISTRAR: 'colab_turno.registrar',
    INVENTARIO_VER: 'colab_inventario.ver',
    INVENTARIO_AJUSTAR: 'colab_inventario.ajustar',
    INVENTARIO_EXPORTAR: 'colab_inventario.exportar',
    ENTRADAS_VER: 'colab_entradas.ver',
    ENTRADAS_CREAR: 'colab_entradas.crear',
    ENTRADAS_APROBAR: 'colab_entradas.aprobar',
    SALIDAS_VER: 'colab_salidas.ver',
    SALIDAS_CREAR: 'colab_salidas.crear',
    SALIDAS_APROBAR: 'colab_salidas.aprobar',
    TRANSFERENCIAS_VER: 'colab_transferencias.ver',
    TRANSFERENCIAS_CREAR: 'colab_transferencias.crear',
    TRANSFERENCIAS_APROBAR: 'colab_transferencias.aprobar',
    CONTEOS_VER: 'colab_conteos.ver',
    CONTEOS_CREAR: 'colab_conteos.crear',
    CONTEOS_EJECUTAR: 'colab_conteos.ejecutar',
    CONTEOS_APROBAR: 'colab_conteos.aprobar',
    PRODUCTOS_VER: 'colab_productos.ver',
    REPORTES_VER: 'colab_reportes.ver',
    REPORTES_EXPORTAR: 'colab_reportes.exportar',
    ACTIVIDAD_VER: 'colab_actividad.ver',
    NOTIFICACIONES_VER: 'colab_notificaciones.ver',
    PERFIL_VER: 'colab_perfil.ver',
    PERFIL_EDITAR: 'colab_perfil.editar',
} as const;

export type TipoPermisoColab = typeof PERMISOS_COLAB[keyof typeof PERMISOS_COLAB];
