export const actividad: Record<string, string> = {
    'actividad.titulo': 'My Activity',
    'actividad.descripcion': 'Event, operations, and sessions history',
    'actividad.timeline': 'Timeline',
    'actividad.bitacora': 'Log',
    'actividad.operaciones': 'Operations',
    'actividad.eventosSeg': 'Security Events',
    'actividad.logins': 'logins',
    'actividad.fallidos': 'failed',
    'actividad.opInventario': 'Inventory Operations',
    'actividad.conteosRealizados': 'Counts Performed',
    'actividad.ultimoLogin': 'Last Login',
    'actividad.ip': 'IP:',
    'actividad.sinLoginReg': 'No login records',
    'actividad.ultimaOp': 'Last Operation',
    'actividad.sinOpReg': 'No operations registered',
    'actividad.desglose': 'Activity Breakdown in the Period',
    'actividad.iniciosSesion': 'Logins',
    'actividad.cronologica': 'Chronological Activity',
    'actividad.eventos': 'events',
    'actividad.sinActividad': 'No activity registered in the period',
    'actividad.tipoEvento': 'Event type',
    'actividad.inicioSesion': 'Login',
    'actividad.loginFallido': 'Failed login',
    'actividad.cierreSesion': 'Logout',
    'actividad.cambioContrasena': 'Password change',
    'actividad.recupContrasena': 'Password recovery',
    'actividad.bloqueoCuenta': 'Account lock',
    'actividad.desbloqueo': 'Account unlock',
    'actividad.dispNuevo': 'New device',
    'actividad.accesoDenegado': 'Access denied',
    'actividad.sesionForzada': 'Forced session',
    'actividad.multIntentos': 'Multiple attempts',
    'actividad.severidad': 'Severity',
    'actividad.informacion': 'Information',
    'actividad.advertencia': 'Warning',
    'actividad.error': 'Error',
    'actividad.critico': 'Critical',
    'actividad.opInventarioTit': 'Inventory Operations',
    'actividad.sinOpFiltros': 'No operations found with the selected filters',
    'actividad.histSesiones': 'Session History',
    'actividad.activa': 'Active',
    'actividad.cerrada': 'Closed',
    'actividad.expirada': 'Expired',
    'actividad.sinSesionesPeriodo': 'No sessions found in the period',
    'actividad.sinEventos': 'No security events found',
    'actividad.sesiones': 'Sessions',
    'actividad.seguridad': 'Security',
    'actividad.inventario': 'Inventory',
    'actividad.conteo': 'Count',
    'actividad.buscarDesc': 'Search in description...',
};
