export const comun: Record<string, string> = {
    'tiempo.ahoraMismo': 'Just now',
    'tiempo.haceMin': '{n} min ago',
    'tiempo.haceHoras': '{n} h ago',
    'tiempo.haceDias': '{n} d ago',

    'comun.cargando': 'Loading...',
    'comun.cargandoPerfil': 'Loading profile...',
    'comun.cargandoDashboard': 'Loading dashboard data...',
    'comun.cargandoTurno': 'Loading shift information...',
    'comun.cargandoTransferencias': 'Loading transfers...',
    'comun.cargandoConteos': 'Loading counts...',
    'comun.cargandoProductos': 'Loading products...',
    'comun.cargandoDetalle': 'Loading details...',
    'comun.cargandoEntradas': 'Loading inbound...',
    'comun.cargandoSalidas': 'Loading outbound...',
    'comun.cargandoStock': 'Loading stock...',
    'comun.cargandoNotificaciones': 'Loading notifications...',
    'comun.cargandoDatos': 'Loading data...',
    'comun.generandoReporte': 'Generating report...',
    'comun.buscandoProductos': 'Searching products...',
    'comun.cancelar': 'Cancel',
    'comun.confirmar': 'Confirm',
    'comun.buscar': 'Search',
    'comun.guardar': 'Save',
    'comun.cerrar': 'Close',
    'comun.exportarCsv': 'Export CSV',
    'comun.filtrar': 'Filter',
    'comun.limpiar': 'Clear',
    'comun.guardarCambios': 'Save changes',
    'comun.producto': 'Product',
    'comun.cantidad': 'Quantity',
    'comun.motivo': 'Reason',
    'comun.estado': 'Status',
    'comun.tipo': 'Type',
    'comun.fecha': 'Date',
    'comun.acciones': 'Actions',
    'comun.descripcion': 'Description',
    'comun.precio': 'Price',
    'comun.stock': 'Stock',
    'comun.sku': 'SKU',
    'comun.almacen': 'Warehouse',
    'comun.todos': 'All',
    'comun.todas': 'All',
    'comun.desde': 'From',
    'comun.hasta': 'To',
    'comun.productoSku': 'Product or SKU...',
    'comun.escribaBuscar': 'Type to search product by name or SKU...',
    'comun.observaciones': 'Optional notes...',
    'comun.tipoDocumento': 'Document type',
    'comun.numDocumento': 'Document number',
    'comun.notasAdicionales': 'Additional notes',
    'comun.notasOpcional': 'Notes (optional)',
    'comun.observacionesCambio': 'Notes about the status change...',
    'comun.sinDocumento': 'No document',
    'comun.factura': 'Invoice',
    'comun.otro': 'Other',
    'comun.ordenCompra': 'Purchase order',
    'comun.guiaRemision': 'Shipment guide',
    'comun.notaEntrega': 'Delivery note',
    'comun.ordenDespacho': 'Dispatch order',
    'comun.motivoEjEntrada': 'E.g.: Supplier purchase, stock replenishment...',
    'comun.motivoEjSalida': 'E.g.: Direct sale, customer dispatch...',
    'comun.numDocEjEntrada': 'E.g.: INV-001234',
    'comun.numDocEjSalida': 'E.g.: DO-001234',
    'comun.anterior': 'Previous',
    'comun.nuevo': 'New',
    'comun.colaborador': 'Collaborator',
    'comun.ip': 'IP',
    'comun.navegador': 'Browser',
    'comun.sistema': 'System',
    'comun.cierre': 'Close',
    'comun.ubicacion': 'Location',
    'comun.programado': 'Scheduled',
    'comun.completado': 'Completed',
    'comun.completada': 'Completed',
    'comun.aprobado': 'Approved',
    'comun.rechazado': 'Rejected',
    'comun.cancelado': 'Cancelled',
    'comun.cancelada': 'Cancelled',
    'comun.pendiente': 'Pending',
    'comun.nombre': 'Name',
    'comun.direccion': 'Address',
    'comun.dia': 'Day',
    'comun.horas': 'Hours',
    'comun.noProductosFiltro': 'No products found',
    'comun.productos': 'products',
    'comun.limpiarFiltros': 'Clear filters',
    'comun.verDetalle': 'View details',
    'comun.completar': 'Complete',
    'comun.ent': 'in',
    'comun.sal': 'out',
    'comun.mov': 'mov.',
    'comun.sinStock': 'Unassigned',
    'comun.ordenTransferencia': 'Transfer order',
    'comun.guiaDespacho': 'Dispatch guide',
    'comun.notaTraslado': 'Transfer note',
    'comun.motivoEjTransferencia': 'E.g.: Restocking, stock redistribution...',
    'comun.numDocEjTransferencia': 'E.g.: TO-001234',
    'comun.stockDisponible': 'Available stock',
    'comun.origen': 'Origin',
    'comun.destino': 'Destination',
    'comun.documento': 'Document',
    'comun.notas': 'Notes',
    'comun.codigo': 'Code',
    'comun.telefono': 'Phone',
    'comun.fechaDesde': 'Date from',
    'comun.fechaHasta': 'Date to',
    'comun.diferencia': 'Difference',
    'comun.usuario': 'User',
    'comun.inicio': 'Start',
    'comun.ultimaActividad': 'Last Activity',

    'toast.campoRequerido': 'Required field',
    'toast.camposRequeridos': 'Required fields',
    'toast.almacenesIguales': 'Same warehouses',
    'toast.stockInsuficiente': 'Insufficient stock',
    'toast.transferenciaCreada': 'Transfer created',
    'toast.estadoActualizado': 'Status updated',
    'toast.entradaRegistrada': 'Inbound registered',
    'toast.salidaRegistrada': 'Outbound registered',
    'toast.conteoProgramado': 'Count scheduled',
    'toast.enProgreso': 'In progress',
    'toast.registrado': 'Registered',
    'toast.loteGuardado': 'Batch saved',
    'toast.sinCambios': 'No changes',
    'toast.cantidadInvalida': 'Invalid quantity',
    'toast.exportIniciada': 'Export started',
    'toast.seleccioneProducto': 'Select a product',
    'toast.seleccioneOrigen': 'Select the origin warehouse',
    'toast.seleccioneDestino': 'Select the destination warehouse',
    'toast.almacenesIgualesMsg': 'Origin and destination warehouses cannot be the same',
    'toast.motivoInvalido': 'Enter a valid reason (minimum 3 characters)',
    'toast.stockInsufMsg': 'Insufficient stock. Available: {disponible}, Requested: {solicitado}',
    'toast.errorCrearTransferencia': 'Error creating transfer',
    'toast.errorActualizarEstado': 'Error updating status',
    'toast.completeCampos': 'Complete all required fields',
    'toast.errorRegistrarEntrada': 'Error registering inbound',
    'toast.errorRegistrarSalida': 'Error registering outbound',
    'toast.errorCargarDatos': 'Error loading initial data',
    'toast.errorCargarProductos': 'Error loading products',
    'toast.errorCargarDetalle': 'Error loading product details',
    'toast.errorCargarNotif': 'Could not load notifications',
    'toast.notifLeida': 'Notification marked as read',
    'toast.errorMarcarNotif': 'Error marking notification',
    'toast.notifArchivada': 'Notification archived',
    'toast.errorArchivarNotif': 'Error archiving notification',
    'toast.notifEliminada': 'Notification deleted',
    'toast.errorEliminarNotif': 'Error deleting notification',
    'toast.todasLeidas': 'All notifications marked as read',
    'toast.errorMarcarTodas': 'Error marking notifications',
    'toast.notifsSelLeidas': '{n} notifications marked as read',
    'toast.leidasArchivadas': 'Read notifications archived',
    'toast.errorArchivarTodas': 'Error archiving notifications',
    'toast.errorRegistrarEntradaTurno': 'Error registering check in',
    'toast.errorRegistrarSalidaTurno': 'Error registering check out',
    'toast.errorCargarPerfil': 'Could not load profile',
    'toast.errorCargarSeguridad': 'Could not load security information',
    'toast.errorCargarPreferencias': 'Could not load preferences',
    'toast.errorCargarSesiones': 'Could not load sessions',
    'toast.errorCargarDispositivos': 'Could not load devices',
    'toast.nombreApellidoReq': 'First name and last name are required',
    'toast.errorActualizarPerfil': 'Could not update profile',
    'toast.ingreseContrasenaActual': 'Enter your current password',
    'toast.contrasenasNoCoinciden': 'Passwords do not match',
    'toast.errorCambiarContrasena': 'Could not change password',
    'toast.errorActualizarSeguridad': 'Could not update security settings',
    'toast.errorGuardarPreferencias': 'Could not save preferences',
    'toast.errorCerrarSesion': 'Could not close session',
    'toast.errorCerrarSesiones': 'Could not close sessions',
    'toast.errorEliminarDisp': 'Could not remove device',
    'toast.errorActualizarDisp': 'Could not update device',
    'toast.errorRenombrarDisp': 'Could not rename device',
    'toast.seleccioneAlmacen': 'Select a warehouse',
    'toast.seleccioneFecha': 'Select the scheduled date',
    'toast.conteoProgramadoMsg': 'Count scheduled successfully',
    'toast.errorCrearConteo': 'Error creating count',
    'toast.errorCargarDetConteo': 'Error loading details',
    'toast.conteoIniciado': 'Count started',
    'toast.errorIniciarConteo': 'Error starting count',
    'toast.cantidadInvalidaMsg': 'Enter a valid quantity (0 or greater)',
    'toast.productoRegistrado': 'Product registered',
    'toast.errorRegistrar': 'Error registering',
    'toast.sinProductosCantidad': 'No products with quantities to register',
    'toast.loteRegistrado': 'Batch registered',
    'toast.errorGuardarLote': 'Error saving batch',
    'toast.errorCargarResumen': 'Error loading activity summary',
    'toast.errorCargarBitacora': 'Error loading log',
    'toast.errorCargarOperaciones': 'Error loading operations',
    'toast.errorCargarSesionesMi': 'Error loading sessions',
    'toast.errorCargarTimeline': 'Error loading timeline',
    'toast.exportBitacora': 'Log export started',
    'toast.exportOperaciones': 'Operations export started',
    'toast.errorCargarResumenRep': 'Error loading report summary',
    'toast.errorCargarMovimientos': 'Error loading movements',
    'toast.errorCargarStockCritico': 'Error loading critical stock',
    'toast.errorCargarActividadRep': 'Error loading activity',

    'contrasena.min12': 'Password must be at least 12 characters',
    'contrasena.mayuscula': 'Must contain at least one uppercase letter',
    'contrasena.minuscula': 'Must contain at least one lowercase letter',
    'contrasena.numero': 'Must contain at least one number',
    'contrasena.especial': 'Must contain at least one special character',
    'contrasena.debil': 'Weak',
    'contrasena.media': 'Medium',
    'contrasena.fuerte': 'Strong',
    'contrasena.muyFuerte': 'Very strong',

    'etiqueta.disponible': 'Available',
    'etiqueta.enTransito': 'In Transit',
    'etiqueta.enCurso': 'In Progress',
    'etiqueta.finalizado': 'Finished',
    'etiqueta.anticipado': 'Early',
    'etiqueta.puntual': 'On time',
    'etiqueta.leveRetraso': 'Slight delay',
    'etiqueta.retraso': 'Late',
    'etiqueta.transfSalida': 'Transfer (Out)',
    'etiqueta.transfEntrada': 'Transfer (In)',
    'etiqueta.programado': 'Scheduled',
    'etiqueta.enProgresoLabel': 'In Progress',
    'etiqueta.completado': 'Completed',
    'etiqueta.aprobado': 'Approved',
    'etiqueta.rechazado': 'Rejected',
    'etiqueta.cancelado': 'Cancelled',

    'contrato.permanente': 'Permanent',
    'contrato.temporal': 'Temporary',
    'contrato.medioTiempo': 'Part-time',
    'contrato.pasantia': 'Internship',
    'contrato.porContrato': 'Contract',

    'misc.noDisponible': 'Not available',
    'misc.nunca': 'Never',

    'login.errorInicioSesion': 'Login error',
    'login.sinAcceso': 'Your account does not have access to the collaborator portal. Verify that your role is correct.',
    'login.errorConexion': 'Server connection error',
};
