export const conteos: Record<string, string> = {
    'conteos.titulo': 'Inventory Counts',
    'conteos.nuevo': 'New Count',
    'conteos.programados': 'Scheduled',
    'conteos.enProgreso': 'In Progress',
    'conteos.finalizadosMes': 'Completed this month',
    'conteos.totalMes': 'Monthly total',
    'conteos.sinRegistros': 'No counts registered',
    'conteos.noEncontrados': 'No counts found with the applied filters',
    'conteos.programarPrimero': 'Schedule first count',
    'conteos.encontrados': 'counts found',
    'conteos.zona': 'Zone:',
    'conteos.parcial': 'Partial',
    'conteos.completo': 'Complete',
    'conteos.iniciar': 'Start count',
    'conteos.continuar': 'Continue count',
    'conteos.aprobar': 'Approve',
    'conteos.rechazar': 'Reject',
    'conteos.volverLista': 'Back to list',
    'conteos.responsable': 'Responsible',
    'conteos.fechaProgramada': 'Scheduled date',
    'conteos.zonaConteo': 'Count zone',
    'conteos.notas': 'Notes',
    'conteos.productosContados': 'Counted products',
    'conteos.discrepancias': 'Discrepancies',
    'conteos.unidFaltantes': 'Missing units',
    'conteos.unidSobrantes': 'Surplus units',
    'conteos.inicio': 'Start:',
    'conteos.fin': 'End:',
    'conteos.programar': 'Schedule Count',
    'conteos.salir': 'Exit',
    'conteos.registrarConteo': 'Register count',
    'conteos.guardarTodo': 'Save all',
    'conteos.stockSistema': 'System stock',
    'conteos.cantidadFisica': 'Physical quantity',
    'conteos.contado': 'Counted',
    'conteos.guardar': 'Save',
    'conteos.sinProductosFiltro': 'No products found with that filter',
    'conteos.parcialDesc': 'Only products from specific zone/category',
    'conteos.completoDesc': 'All products in the warehouse',
    'conteos.todasCategorias': 'All categories',
    'conteos.instrucciones': 'Instructions or notes for the count...',
    'conteos.ajustarStock': 'Adjust stock automatically',
    'conteos.ajustarDesc': 'Product stock will be updated according to physical count quantities',
    'conteos.aprobarIrreversible': 'Stock adjustment upon approval is irreversible.',
    'conteos.cancelarInfo': 'Count data will be preserved but the count will be marked as cancelled.',
    'conteos.rechazarInfo': 'The count can be resumed from "In Progress" status to correct observations.',
    'conteos.categoriaEspecifica': 'Specific category',
    'conteos.buscarProductoSku': 'Search product by name or SKU...',
    'conteos.ejZona': 'Ex: Aisle A, Shelf 3...',
};
