export const inventario: Record<string, string> = {
    'entradas.titulo': 'Inventory Inbound',
    'entradas.nueva': 'New Inbound',
    'entradas.sinRegistros': 'No inbound records',
    'entradas.noEncontrados': 'No inbound records found',
    'entradas.registrarPrimera': 'Register first inbound',
    'entradas.registrar': 'Register Inbound',

    'salidas.titulo': 'Inventory Outbound',
    'salidas.nueva': 'New Outbound',
    'salidas.sinRegistros': 'No outbound records',
    'salidas.noEncontrados': 'No outbound records found',
    'salidas.registrarPrimera': 'Register first outbound',
    'salidas.registrar': 'Register Outbound',
    'salidas.stockDisponible': 'Available stock:',

    'stock.titulo': 'General Stock',
    'stock.buscar': 'Search product',
    'stock.placeholder': 'Name or SKU...',
    'stock.todosAlmacenes': 'All warehouses',
    'stock.noEncontrados': 'No products found',
    'stock.intentaFiltros': 'Try different search filters',
    'stock.productos': 'products',
    'stock.almacen': 'Warehouse',
    'stock.producto': 'Product',
    'stock.categoria': 'Category',
    'stock.precio': 'Price',
    'stock.stockCol': 'Stock',
    'stock.min': 'Min.',
    'stock.estado': 'Status',

    'transferencias.titulo': 'Warehouse Transfers',
    'transferencias.nueva': 'New Transfer',
    'transferencias.sinRegistros': 'No transfers registered',
    'transferencias.noEncontrados': 'No transfers found with the applied filters',
    'transferencias.crearPrimera': 'Create first transfer',
    'transferencias.crear': 'Create Transfer',
    'transferencias.encontradas': 'transfers found',
    'transferencias.detalle': 'Transfer Details',
    'transferencias.unidades': 'units',
    'transferencias.almacenOrigen': 'Origin Warehouse',
    'transferencias.almacenDestino': 'Destination Warehouse',
    'transferencias.seleccioneOrigen': 'Select origin',
    'transferencias.seleccioneDestino': 'Select destination',
    'transferencias.soloAsignados': 'Assigned warehouses only',
    'transferencias.todosActivos': 'All active warehouses',
    'transferencias.pendienteInfo': 'The transfer will remain Pending until approved. Stock will not change until marked as Completed.',
    'transferencias.marcarEnTransito': 'Mark In Transit',
    'transferencias.completar': 'Complete Transfer',
    'transferencias.cancelar': 'Cancel Transfer',
    'transferencias.alCompletar': 'Upon completion, the product stock will be deducted from the origin warehouse.',
    'transferencias.accionIrreversible': 'This action cannot be undone.',
    'transferencias.movimientoStock': 'Stock movement',
    'transferencias.solicitadoPor': 'Requested by',
    'transferencias.enTransito': 'In Transit',
};
