export const notificaciones: Record<string, string> = {
    'notif.titulo': 'Notifications',
    'notif.descripcion': 'Manage your system notifications',
    'notif.enTotal': 'total',
    'notif.marcarLeidas': 'Mark all as read',
    'notif.archivarLeidas': 'Archive read',
    'notif.bandeja': 'Inbox',
    'notif.sinLeer': 'Unread',
    'notif.archivadas': 'Archived',
    'notif.buscar': 'Search notifications...',
    'notif.todosLosTipos': 'All types',
    'notif.exito': 'Success',
    'notif.importante': 'Important',
    'notif.sistema': 'System',
    'notif.seleccionadas': 'notification(s) selected',
    'notif.marcarSelLeidas': 'Mark as read',
    'notif.seleccionarTodas': 'Select all',
    'notif.nueva': 'New',
    'notif.marcarLeida': 'Mark as read',
    'notif.archivar': 'Archive',
    'notif.eliminar': 'Delete',
    'notif.sinSinLeer': 'No unread notifications',
    'notif.alDia': "You're all caught up!",
    'notif.sinArchivadas': 'No archived notifications',
    'notif.archivadasDesc': 'Notifications you archive will appear here',
    'notif.sinNotif': 'No notifications',
    'notif.sinNotifDesc': "You'll receive notifications when there's system activity",
    'notif.informacion': 'Information',
    'notif.advertencia': 'Warning',
    'notif.pagina': 'Page',
    'notif.de': 'of',
    'notif.notificaciones': 'notifications',
};
