export const perfil: Record<string, string> = {
    'perfil.sinCargo': 'No position assigned',
    'perfil.desde': 'Since',
    'perfil.ultimoAcceso': 'Last access:',
    'perfil.verificado': 'Verified',

    'perfil.general': 'General',
    'perfil.seguridad': 'Security',
    'perfil.preferencias': 'Preferences',
    'perfil.sesiones': 'Sessions',
    'perfil.dispositivos': 'Devices',

    'perfil.infoPersonal': 'Personal Information',
    'perfil.editar': 'Edit',
    'perfil.nombre': 'First Name',
    'perfil.apellido': 'Last Name',
    'perfil.telefono': 'Phone',
    'perfil.genero': 'Gender',
    'perfil.noEspecificado': 'Not specified',
    'perfil.masculino': 'Male',
    'perfil.femenino': 'Female',
    'perfil.contactoEmergencia': 'Emergency Contact',
    'perfil.nombreContacto': 'Contact name',
    'perfil.nombreCompleto': 'Full name',
    'perfil.telefonoEmergencia': 'Emergency phone',
    'perfil.ejTelefono': 'E.g.: +504 9999-9999',
    'perfil.identidad': 'ID Number',
    'perfil.noRegistrada': 'Not registered',
    'perfil.fechaNacimiento': 'Date of birth',
    'perfil.noRegistrado': 'Not registered',

    'perfil.infoLaboral': 'Work Information',
    'perfil.codigo': 'Code',
    'perfil.cargo': 'Position',
    'perfil.sinCargoPuesto': 'No position',
    'perfil.tipoContrato': 'Contract type',
    'perfil.fechaIngreso': 'Start date',
    'perfil.almacenPrincipal': 'Main warehouse',

    'perfil.rolesAlmacenes': 'Roles & Warehouses',
    'perfil.rolesAsignados': 'Assigned roles',
    'perfil.sinRoles': 'No roles assigned',
    'perfil.almacenesAsignados': 'Assigned warehouses',
    'perfil.sinAlmacenes': 'No warehouses assigned',

    'seguridad.contrasena': 'Password',
    'seguridad.estadoContrasena': 'Password status',
    'seguridad.contrasenaTemporal': 'Temporary password - must be changed',
    'seguridad.ultimoCambio': 'Last change:',
    'seguridad.dias': 'days',
    'seguridad.cambiarContrasena': 'Change password',
    'seguridad.contrasenaActual': 'Current password',
    'seguridad.ingreseActual': 'Enter your current password',
    'seguridad.nuevaContrasena': 'New password',
    'seguridad.minCaracteres': 'Minimum 12 characters',
    'seguridad.12Caracteres': '12+ characters',
    'seguridad.mayuscula': 'Uppercase',
    'seguridad.minuscula': 'Lowercase',
    'seguridad.numero': 'Number',
    'seguridad.especial': 'Special',
    'seguridad.confirmarContrasena': 'Confirm new password',
    'seguridad.repitaContrasena': 'Repeat the new password',
    'seguridad.noCoinciden': 'Passwords do not match',

    'seguridad.configuracion': 'Security Settings',
    'seguridad.2fa': 'Two-factor authentication (2FA)',
    'seguridad.2faDesc': 'Add an extra layer of security to your account',
    'seguridad.2faInactivo': 'Not configured',
    'seguridad.2faActivo': 'Active',
    'seguridad.activar2fa': 'Enable two-factor authentication',
    'seguridad.desactivar2fa': 'Disable 2FA',
    'seguridad.desactivarDesc': 'To disable two-factor authentication, enter your current password',
    'seguridad.contrasenaRequerida': 'Enter your password to continue',
    'seguridad.seleccionarMetodo': 'Select verification method',
    'seguridad.metodoVerificacion': 'Verification method',
    'seguridad.correoElectronico': 'Email',
    'seguridad.correoDesc': 'Receive a verification code in your email',
    'seguridad.appAutenticadora': 'Authenticator app',
    'seguridad.appDesc': 'Use Google Authenticator, Authy or another compatible app',
    'seguridad.configurando': 'Setting up...',
    'seguridad.cancelar': 'Cancel',
    'seguridad.verificarCodigo': 'Verify code',
    'seguridad.escanearQR': 'Scan this QR code with your authenticator app',
    'seguridad.codigoEnviado': 'A verification code has been sent to your email',
    'seguridad.ingresarCodigo': '6-digit code',
    'seguridad.codigo6Digitos': 'The code must be 6 digits',
    'seguridad.codigoIncorrecto': 'The verification code is incorrect',
    'seguridad.confirmarActivacion': 'Confirm and activate',
    'seguridad.sesionesMaximas': 'Maximum simultaneous sessions',
    'seguridad.sesion': 'session',
    'seguridad.sesiones': 'sessions',
    'seguridad.controlSesionesAdmin': 'This value is configured by the system administrator',
    'seguridad.guardarConfig': 'Save settings',

    'seguridad.actividadReciente': 'Recent Security Activity',
    'seguridad.sesionesActivas': 'Active sessions',
    'seguridad.ultimoCambioContrasena': 'Last password change',
    'seguridad.sinActividad': 'No recent activity',

    'preferencias.temaColor': 'Color Theme',
    'preferencias.seleccionaColor': 'Select the primary color for the interface',
    'preferencias.interfaz': 'Interface',
    'preferencias.sidebarCompacto': 'Compact sidebar',
    'preferencias.sidebarDesc': 'Reduces the width of the side menu',
    'preferencias.idioma': 'Language',
    'preferencias.zonaHoraria': 'Time zone',
    'preferencias.notificaciones': 'Notifications',
    'preferencias.sonido': 'Notification sound',
    'preferencias.sonidoDesc': 'Play a sound when receiving notifications',
    'preferencias.escritorio': 'Desktop notifications',
    'preferencias.escritorioDesc': 'Show operating system notifications',
    'preferencias.guardar': 'Save preferences',

    'sesiones.titulo': 'Active Sessions',
    'sesiones.cerrarTodas': 'Close all others',
    'sesiones.actual': 'Current',
    'sesiones.iniciada': 'Started:',
    'sesiones.ultimaActividad': 'Last activity:',
    'sesiones.sinSesiones': 'No active sessions',

    'dispositivos.titulo': 'Registered Devices',
    'dispositivos.tituloConfianza': 'My Devices',
    'dispositivos.descripcion': 'Here you can view and manage the devices you have logged in from. Mark the ones you recognize as trusted for extra security.',
    'dispositivos.confiable': 'Trusted',
    'dispositivos.enLinea': 'Online',
    'dispositivos.navegadorDesconocido': 'Unknown browser',
    'dispositivos.soDesconocido': 'Unknown OS',
    'dispositivos.registrado': 'Registered:',
    'dispositivos.ultimoUso': 'Last used:',
    'dispositivos.confirmadoEn': 'Trusted since:',
    'dispositivos.sinDispositivos': 'No registered devices',
    'dispositivos.sinDispositivosDesc': 'Devices will be registered automatically when you sign in.',
    'dispositivos.marcarConfiable': 'Mark as trusted',
    'dispositivos.revocarConfianza': 'Revoke trust',
    'dispositivos.renombrar': 'Rename device',
    'dispositivos.eliminar': 'Remove device',
    'dispositivos.nombreMinimo': 'Name must be at least 2 characters',
};
