export const portal: Record<string, string> = {
    'portal.titulo': 'Collaborator Portal',
    'portal.bodega': 'Warehouse Portal',
    'portal.soporte': 'Support',
    'portal.cerrarSesion': 'Log Out',
    'portal.cerrarMenu': 'Close menu',

    'menu.principal': 'Main',
    'menu.operaciones': 'Operations',
    'menu.consultas': 'Queries',
    'menu.personal': 'Personal',
    'menu.inicio': 'Home',
    'menu.miTurno': 'My Shift',
    'menu.inventario': 'Inventory',
    'menu.stockGeneral': 'General Stock',
    'menu.entradas': 'Inbound',
    'menu.salidas': 'Outbound',
    'menu.transferencias': 'Transfers',
    'menu.conteos': 'Counts',
    'menu.productos': 'Products',
    'menu.reportes': 'Reports',
    'menu.miActividad': 'My Activity',
    'menu.notificaciones': 'Notifications',
    'menu.miPerfil': 'My Profile',

    'header.notificaciones': 'Notifications',
    'header.marcarTodasLeidas': 'Mark all as read',
    'header.noHayNotificaciones': 'No notifications',
    'header.verTodas': 'View all notifications',
    'header.miActividad': 'My Activity',
    'header.miTurno': 'My Shift',

    'rol.jefeBodega': 'Warehouse Manager',
    'rol.supervisor': 'Supervisor',
    'rol.inventarista': 'Inventory Clerk',
    'rol.recepcionista': 'Receptionist',
    'rol.despachador': 'Dispatcher',
    'rol.auxiliar': 'Assistant',
    'rol.consulta': 'Read Only',
    'rol.colaborador': 'Collaborator',
};
