export const productos: Record<string, string> = {
    'productos.catalogo': 'Product Catalog',
    'productos.activos': 'Active',
    'productos.agotados': 'Out of Stock',
    'productos.stockBajo': 'Low Stock',
    'productos.inactivos': 'Inactive',
    'productos.buscar': 'Search product',
    'productos.placeholder': 'Name, SKU...',
    'productos.categoria': 'Category',
    'productos.todas': 'All',
    'productos.todos': 'All',
    'productos.limpiarFiltros': 'Clear filters',
    'productos.filtrosAvanzados': 'Advanced filters',
    'productos.marca': 'Brand',
    'productos.precioDesde': 'Price from (L)',
    'productos.precioHasta': 'Price to (L)',
    'productos.aplicarFiltros': 'Apply filters',
    'productos.noEncontrados': 'No products found',
    'productos.intentaFiltros': 'Try different search filters',
    'productos.min': 'Min:',
    'productos.inactivo': 'Inactive',
    'productos.destacado': 'Featured',
    'productos.verDetalle': 'View details',
    'productos.mostrando': 'Showing page',
    'productos.de': 'of',
    'productos.resultados': 'results',
    'productos.volverCatalogo': 'Back to catalog',
    'productos.activo': 'Active',
    'productos.precioVenta': 'Sale price',
    'productos.precioAnterior': 'Previous price',
    'productos.costo': 'Cost',
    'productos.margen': 'Margin',
    'productos.stockActual': 'Current stock',
    'productos.uds': 'units',
    'productos.stockMinimo': 'Minimum stock',
    'productos.estadoStock': 'Stock status',
    'productos.peso': 'Weight',
    'productos.kg': 'kg',
    'productos.creado': 'Created',
    'productos.ultimaActualizacion': 'Last updated',
    'productos.informacion': 'Information',
    'productos.movimientos': 'Inventory movements',
    'productos.descripcion': 'Description',
    'productos.sinDescripcion': 'This product has no detailed description.',
    'productos.historialMov': 'Movement history',
    'productos.todosLosTipos': 'All types',
    'productos.ajustes': 'Adjustments',
    'productos.devoluciones': 'Returns',
    'productos.sinMovimientos': 'No movements registered',
    'productos.entradas': 'Inbound',
    'productos.salidas': 'Outbound',
    'productos.transferencias': 'Transfers',
    'productos.stockAnterior': 'Previous stock',
    'productos.stockNuevo': 'New stock',
};
