export const reportes: Record<string, string> = {
    'reportes.titulo': 'Reports',
    'reportes.descripcion': 'Inventory queries and analysis',
    'reportes.resumen': 'Summary',
    'reportes.movimientos': 'Movements',
    'reportes.stockCritico': 'Critical Stock',
    'reportes.miActividad': 'My Activity',
    'reportes.generando': 'Generating report...',
    'reportes.totalProductos': 'Total Products',
    'reportes.valorInventario': 'Inventory Value',
    'reportes.precioXStock': 'Price x Stock',
    'reportes.entradasSalidas': 'Inbound / Outbound',
    'reportes.enElPeriodo': 'In the period',
    'reportes.alertasStock': 'Stock Alerts',
    'reportes.productosMasMovidos': 'Most Moved Products',
    'reportes.sinMovPeriodo': 'No movements in the period',
    'reportes.movPorCategoria': 'Movements by Category',
    'reportes.sinDatosCategorias': 'No category data',
    'reportes.movInventario': 'Inventory Movements',
    'reportes.registros': 'records',
    'reportes.tipoOperacion': 'Operation type',
    'reportes.entrada': 'Inbound',
    'reportes.salida': 'Outbound',
    'reportes.recepcion': 'Reception',
    'reportes.despacho': 'Dispatch',
    'reportes.ajusteMas': 'Adjustment (+)',
    'reportes.ajusteMenos': 'Adjustment (-)',
    'reportes.transferencia': 'Transfer',
    'reportes.pagina': 'Page',
    'reportes.totalCriticos': 'Total Critical',
    'reportes.agotado': 'Out of Stock',
    'reportes.bajo': 'Low',
    'reportes.sinStockCritico': 'No products with critical stock',
    'reportes.totalOperaciones': 'Total Operations',
    'reportes.noMovFiltros': 'No movements found with the selected filters',
    'reportes.noOpPeriodo': 'You have no operations registered in the period',
    'reportes.histOperaciones': 'Operations History',
    'reportes.buscarProducto': 'Search product...',
    'reportes.placeholderBuscar': 'Product name or SKU...',
};
