export const turno: Record<string, string> = {
    'turno.turnoHoy': "Today's Shift",
    'turno.resumenSemanal': 'Weekly Summary',
    'turno.historial': 'History',
    'turno.almacen': 'Warehouse',
    'turno.inicioProgramado': 'Scheduled start',
    'turno.finProgramado': 'Scheduled end',
    'turno.entrada': 'Check in',
    'turno.salida': 'Check out',
    'turno.pendiente': 'Pending',
    'turno.tiempoEnTurno': 'Time on shift',
    'turno.totalHoras': 'Total hours worked',
    'turno.registrarEntrada': 'Check In',
    'turno.registrarSalida': 'Check Out',
    'turno.actividadTurno': 'Shift Activity',
    'turno.sinTurno': 'No shift scheduled for today',
    'turno.sinTurnoDesc': "You don't have a shift assigned for today.",
    'turno.consultaSupervisor': 'Contact your supervisor if you think this is an error.',
    'turno.turnosTotales': 'Total Shifts',
    'turno.completados': 'Completed',
    'turno.horasTrabajadas': 'Hours Worked',
    'turno.puntualidad': 'Punctuality',
    'turno.turnosSemana': "This Week's Shifts",
    'turno.sinTurnosSemana': 'No shifts scheduled this week',
    'turno.historialTurnos': 'Shift History',
    'turno.sinHistorial': 'No shift history',
    'turno.registrarEntradaModal': 'Check In',
    'turno.registrarSalidaModal': 'Check Out',
    'turno.entradaDesc': "You're about to check in for your shift. You can add optional notes.",
    'turno.salidaDesc': "You're about to check out and end your shift. You can add optional notes.",
    'turno.notasOpcional': 'Notes (optional)',
    'turno.ejEntrada': 'E.g.: Normal shift start, all clear...',
    'turno.ejSalida': 'E.g.: Shift completed without incidents...',
    'turno.horaActual': 'Current time:',
    'turno.confirmarEntrada': 'Confirm Check In',
    'turno.confirmarSalida': 'Confirm Check Out',
    'turno.operacion': 'Operation',
    'turno.hora': 'Time',
    'turno.notas': 'Notes',
};
